### ISSUE TITLE
Unhandled Exceptions: building native assets failed

### ISSUE THREAD

**Issue by JM3214** [nmfisher/thermion#61]
Hoping someone might be able to help with this. 

```
`Unhandled exception:
Invalid argument(s): Illegal character in path
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1841:11)
#1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1929:9)
#2      new _Uri.file (dart:core/uri.dart:1808:11)
#3      FileSystemEntity.uri (dart:io/file_system_entity.dart:244:22)
#4      main.<anonymous closure> (file:///C:/Users/jackm/AppData/Local/Pub/Cache/hosted/pub.dev/thermion_dart-0.1.1+5/hook/build.dart:187:27)
<asynchronous suspension>
#5      build (package:native_assets_cli/src/api/build.dart:94:3)
<asynchronous suspension>
#6      main (file:///C:/Users/jackm/AppData/Local/Pub/Cache/hosted/pub.dev/thermion_dart-0.1.1+5/hook/build.dart:8:3)
<asynchronous suspension>
Building native assets for package:thermion_dart failed.
file:///C:/Users/jackm/AppData/Local/Pub/Cache/hosted/pub.dev/thermion_dart-0.1.1+5/hook/build.dart returned with exit code: 255.
To reproduce run:
C:\Users\jackm\flutter\bin\dart --packages=C:\Users\jackm\OneDrive\Documents\GitHub\Simple_Machine_Control\simple_excavator_mc\.dart_tool\package_config.json C:\Users\jackm\AppData\Local\Pub\Cache\hosted\pub.dev\thermion_dart-0.1.1+5\hook\build.dart --config=C:\Users\jackm\OneDrive\Documents\GitHub\Simple_Machine_Control\simple_excavator_mc\.dart_tool\native_assets_builder\c90fbe241c81ff25664205a12660aef7\config.json
stderr:
Unhandled exception:
Invalid argument(s): Illegal character in path
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1841:11)
#1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1929:9)
#2      new _Uri.file (dart:core/uri.dart:1808:11)
#3      FileSystemEntity.uri (dart:io/file_system_entity.dart:244:22)
#4      main.<anonymous closure> (file:///C:/Users/jackm/AppData/Local/Pub/Cache/hosted/pub.dev/thermion_dart-0.1.1+5/hook/build.dart:187:27)
<asynchronous suspension>
#5      build (package:native_assets_cli/src/api/build.dart:94:3)
<asynchronous suspension>
#6      main (file:///C:/Users/jackm/AppData/Local/Pub/Cache/hosted/pub.dev/thermion_dart-0.1.1+5/hook/build.dart:8:3)
<asynchronous suspension>

stdout:


Target native_assets failed: Error: Building native assets failed. See the logs for more details.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\jackm\flutter\bin\flutter.bat'' finished with non-zero exit value 1` 
```

Happens when i try to build from the example repo as well. 
Long term I need to be able to load and render dxf files on device.  
Thanks!

**Comment by nmfisher** [comment]
Are you building for Android on Windows?

Also I can't say I'm familiar with DXF but it looks like it's supported by assimp, so it should be feasible to add support (though we'd probably want to introduce dynamic linking for that kind of thing).

**Comment by JM3214** [comment]
I'm trying to build on windows for android primarily, but also have tried to build for windows with no luck. 
This is a flutter application.

**Comment by nmfisher** [comment]
Can you try cloning/editing the example project to use the following overridden:
```yaml
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  thermion_flutter: ^0.1.1+10
dependency_overrides:
  native_toolchain_c:
    git:
      url: https://github.com/nmfisher/native.git
      path: pkgs/native_toolchain_c
      ref: windows_dll_fix```

then run:
```
flutter clean
flutter packages upgrade
flutter run -d windows
```

Let's try building for Windows first, then deal with Android next.

**Comment by JM3214** [comment]
Thanks mate, 
I tried that. Unfortunately output was basically the same.  
````
PS C:\Users\jackm\Downloads\thermion_examples\flutter\example\lib> flutter run
Changing current working directory to: C:\Users\jackm\Downloads\thermion_examples\flutter\example
Resolving dependencies... (1.1s)
Downloading packages...
  collection 1.18.0 (1.19.0 available)
  flutter_lints 1.0.4 (4.0.0 available)
  image 3.2.2 (4.2.0 available)
  lints 1.0.1 (4.0.0 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  native_assets_cli 0.6.1 (0.7.0 available)
! native_toolchain_c 0.4.2 from git https://github.com/nmfisher/native.git at 8d11bc in pkgs/native_toolchain_c (overridden)
Got dependencies!
6 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib\main.dart on SM T713 in debug mode...
Unhandled exception:
Invalid argument(s): Illegal character in path
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1841:11)
#1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1929:9)
#2      new _Uri.file (dart:core/uri.dart:1808:11)
#3      FileSystemEntity.uri (dart:io/file_system_entity.dart:244:22)
#4      main.<anonymous closure> (file:///C:/Users/jackm/AppData/Local/Pub/Cache/hosted/pub.dev/thermion_dart-0.1.1+5/hook/build.dart:187:27)
<asynchronous suspension>
#5      build (package:native_assets_cli/src/api/build.dart:94:3)
<asynchronous suspension>
#6      main (file:///C:/Users/jackm/AppData/Local/Pub/Cache/hosted/pub.dev/thermion_dart-0.1.1+5/hook/build.dart:8:3)
<asynchronous suspension>
Building native assets for package:thermion_dart failed.
file:///C:/Users/jackm/AppData/Local/Pub/Cache/hosted/pub.dev/thermion_dart-0.1.1+5/hook/build.dart returned with exit code: 255.
To reproduce run:
C:\Users\jackm\flutter\bin\dart --packages=C:\Users\jackm\Downloads\thermion_examples\flutter\example\.dart_tool\package_config.json C:\Users\jackm\AppData\Local\Pub\Cache\hosted\pub.dev\thermion_dart-0.1.1+5\hook\build.dart --config=C:\Users\jackm\Downloads\thermion_examples\flutter\example\.dart_tool\native_assets_builder\9a643e8009926c9a7e816f0a4b74f07a\config.json
stderr:
Unhandled exception:
Invalid argument(s): Illegal character in path
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1841:11)
#1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1929:9)
#2      new _Uri.file (dart:core/uri.dart:1808:11)
#3      FileSystemEntity.uri (dart:io/file_system_entity.dart:244:22)
#4      main.<anonymous closure> (file:///C:/Users/jackm/AppData/Local/Pub/Cache/hosted/pub.dev/thermion_dart-0.1.1+5/hook/build.dart:187:27)
<asynchronous suspension>
#5      build (package:native_assets_cli/src/api/build.dart:94:3)
<asynchronous suspension>
#6      main (file:///C:/Users/jackm/AppData/Local/Pub/Cache/hosted/pub.dev/thermion_dart-0.1.1+5/hook/build.dart:8:3)
<asynchronous suspension>

stdout:


Target native_assets failed: Error: Building native assets failed. See the logs for more details.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\jackm\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Running Gradle task 'assembleDebug'...                             13.3s
Error: Gradle task assembleDebug failed with exit code 1
````

**Comment by nmfisher** [comment]
That still looks like it's launching for Android, not for Windows?

**Comment by JM3214** [comment]
Sorry you're correct. I think i copied the wrong output. 
Its working now, I had to: 
```
- `flutter config 
- flutter config --enable-windows-desktop 
``` 
Still no luck for android though.

**Comment by nmfisher** [comment]
> Sorry you're correct. I think i copied the wrong output. Its working now, I had to:
> 
> ```
> - `flutter config 
> - flutter config --enable-windows-desktop 
> ```
> 
> Still no luck for android though.

OK thanks - I was 99% sure that the Android problem was a different issue, but that's confirmed it. I'll take a look at it now.

**Comment by nmfisher** [comment]
Can you try building for Android with `thermion_flutter: 0.1.1+12`?

**Comment by JM3214** [comment]
Thanks mate, it builds now! Only other thing i did was change the min sdk to 24. 
Its not super stable on my device (s23 ultra) but it should be a good starting point.

**Comment by nmfisher** [comment]
> Thanks mate, it builds now! Only other thing i did was change the min sdk to 24. 
> 
> Its not super stable on my device (s23 ultra) but it should be a good starting point. 

Can you open a new issue about the instability issues you're seeing? That doesn't sound good and should be fixed ASAP.
